/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'msd-sk' at '17/01/20 9:18' with Gradle 3.0
 *
 * @author msd-sk, @date 17/01/20 9:18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
